Allow directory trees in dotfiles lists
geerlingguy/ansible-role-dotfiles pull request #13
Opened 2017-05-15 02:50 UTC by yn

Consider a directory tree layout in dotfiles layout like this:

```
dotfiles_files:
  - .gitconfig
  - .gitignore_global
  - .ssh/config
```

The current codebase supports this in a fairly straightforward manner, except it doesn't create parent directories like `.ssh` 

This PR fixes that by adding a play that creates parent directories.

2017-05-31 13:55 UTC, oxyc commented
I already opened up a PR for this #12. That PR doesn't have `follow: yes` though. Is it necessary?

2017-06-06 00:20 UTC, yn commented
It is not strictly speaking necessary, but it does allow you to have links
to subdirectories instead of subdirectories, if you pre-create them.

On Wed, May 31, 2017 at 6:55 AM, Oskar Schöldström <notifications@github.com
> wrote:

> I already opened up a PR for this #12
> <https://github.com/geerlingguy/ansible-role-dotfiles/pull/12>. That PR
> doesn't have follow: yes though. Is it necessary?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/geerlingguy/ansible-role-dotfiles/pull/13#issuecomment-305193983>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAA8_bItMlJyX4qlD1eSd072bkdkquKlks5r_XFFgaJpZM4NanIT>
> .
>

2018-02-27 11:09 UTC, oxyc commented
@yn you should add `become: no` as well (geerlingguy often uses become:yes in the main playbook).

I can then close my PR and try and poke @geerlingguy to see if he can merge this :)

2018-03-16 06:03 UTC, yn commented
@oxyc done

2018-12-29 16:06 UTC, cbracco commented
Would also love to see this get merged! 😄 cc @geerlingguy ...anything in particular preventing this from happening? Happy to help if I can.

2022-08-20 12:13 UTC, tgallacher commented
would love to see this merged

2024-12-04 12:57 UTC, jaulz commented
@geerlingguy any chance to get this still merged? 😊

2024-12-04 18:08 UTC, geerlingguy requested changes
A couple quick fixes for linting.

2024-12-04 18:08 UTC, geerlingguy commented on tasks/main.yml
> +    follow: yes
```suggestion
    follow: true
```

2024-12-04 18:08 UTC, geerlingguy commented on tasks/main.yml
> +  become: no
```suggestion
  become: false
```

2024-12-04 18:20 UTC, geerlingguy approved these changes

2024-12-04 18:20 UTC, merged

2024-12-04 19:43 UTC, jaulz commented
Wow, I didn't expect such a fast response. Thanks a lot for your work! ☺️

2024-12-05 05:11 UTC, geerlingguy commented
Heh, honestly this PR just slipped through the cracks. Glad you brought it back up :)

2024-12-05 05:13 UTC, geerlingguy commented
Hmm... after merging this in, I spotted an error in my mac-dev-playbook's CI run: https://github.com/geerlingguy/mac-dev-playbook/actions/runs/12173583322

```
TASK [Run .osx dotfiles.] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/Users/runner/.osx --no-restart", "msg": "[Errno 13] Permission denied: b'/Users/runner/.osx'", "rc": 13, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```